apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-conf
  namespace: nginx-ingress
data:
  proxy-read-timeout: "180"
  proxy-send-timeout: "180"
  proxy-body-size: "50m"
  ssl-protocols: TLSv1.2 TLSv1.3
